####    Site settings    ####

title: My digital CV
email: nicholas.foss@comshark.com

####    Build settings    ####

# Specify markdown syntax: https://kramdown.gettalong.org/syntax.html
markdown: kramdown
theme: jekyll-theme-minimal